 
  const CarData=  [
    
        {
          car_brand: "Toyota",
          car_model: "Camry",
          car_price: 25000,
          car_image:'toyota_camry.jpg',
          number_of_seats: 5,
          Drive_Type: "Front-wheel drive",
          transmission: "Automatic",
          year: 2021,
          fuel_type: "Gasoline",
          Engine_size: "2.5L",
          doors: 4,
          cylinder: 4,
          color:"black"
      },
      {
          car_brand: "Honda",
          car_model: "Civic",
          car_price: 22000,
          car_image:'honda-civic.jpg',
          number_of_seats: 5,
          Drive_Type: "Front-wheel drive",
          transmission: "Automatic",
          year: 2021,
          fuel_type: "Gasoline",
          Engine_size: "2.0L",
          doors: 4,
          cylinder: 4,
          color:"red"
      },
      {
        car_brand: "Ford",
        car_model: "Mustang",
        car_price: 45000,
        car_image:'Ford-Mustang.jpg',
        number_of_seats: 4,
        Drive_Type: "Rear-wheel drive",
        transmission: "Automatic",
        year: 2021,
        fuel_type: "Gasoline",
        Engine_size: "5.0L",
        doors: 2,
        cylinder: 8,
        color:"white"
    },
    {
        car_brand: "Chevrolet",
        car_model: "Impala",
        car_price: 28000,
        car_image:'Chevrolet-Impala.jpg',
        number_of_seats: 5,
        Drive_Type: "Front-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.5L",
        doors: 4,
        cylinder: 4,
        color:"red"
    },
    {
        car_brand: "Nissan",
        car_model: "Altima",
        car_price: 26000,
        car_image:'Nissan_Altima.jpg',
        number_of_seats: 5,
        Drive_Type: "Front-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.5L",
        doors: 4,
        cylinder: 4,
        color:"white"
    },
    {
        car_brand: "BMW",
        car_model: "3 Series",
        car_price: 40000,
        car_image:'bmw-3-series.jpg',
        number_of_seats: 5,
        Drive_Type: "Rear-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.0L",
        doors: 4,
        cylinder: 4,
        color:"white"
    },
    {
        car_brand: "Mercedes-Benz",
        car_model: "C-Class",
        car_price: 42000,
        car_image:'Mercedes_Benz_C_Class.jpg',
        number_of_seats: 5,
        Drive_Type: "All-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.0L",
        doors: 4,
        cylinder: 4,
        color:"silver"
    },
    {
        car_brand: "Audi",
        car_model: "A4",
        car_price: 38000,
        car_image:'audi_A4.jpg',
        number_of_seats: 5,
        Drive_Type: "All-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.0L",
        doors: 4,
        cylinder: 4,
        color:"navy blue"
    },
    {
        car_brand: "Kia",
        car_model: "Optima",
        car_price: 23000,
        car_image:'Kia_optima.jpg',
        number_of_seats: 5,
        Drive_Type: "Front-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.5L",
        doors: 4,
        cylinder: 4,
        color:"navy_blue"
    },
    {
        car_brand: "Hyundai",
        car_model: "Sonata",
        car_price: 24000,
        car_image:'hyundai-sonata.jpg',
        number_of_seats: 5,
        Drive_Type: "Front-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.5L",
        doors: 4,
        cylinder: 4,
        color:"black"
    },
    {
        car_brand: "Mazda",
        car_model: "Mazda6",
        car_price: 26000,
        car_image:'mazda6.jpg',
        number_of_seats: 5,
        Drive_Type: "Front-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.5L",
        doors: 4,
        cylinder: 4,
        color:"silver"
    },
    {
        car_brand: "Subaru",
        car_model: "Legacy",
        car_price: 27000,
        car_image:'Subaru_Legacy.jpg',
        number_of_seats: 5,
        Drive_Type: "All-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.5L",
        doors: 4,
        cylinder: 4,
        color:"black"
    },
    {
        car_brand: "Lexus",
        car_model: "ES",
        car_price: 45000,
        car_image:'Lexus-ES.jpg',
        number_of_seats: 5,
        Drive_Type: "Front-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.5L",
        doors: 4,
        cylinder: 4,
        color:"silver"

    },
    {
        car_brand: "Volvo",
        car_model: "S60",
        car_price: 43000,
        car_image:'volvo_s60.jpg',
        number_of_seats: 5,
        Drive_Type: "All-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.0L",
        doors: 4,
        cylinder: 4,
        color:"white"
    },
    {
        car_brand: "Jaguar",
        car_model: "XE",
        car_price: 48000,
        car_image:'jaguar-XE.jpg',
        number_of_seats: 5,
        Drive_Type: "All-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: "2.0L",
        doors: 4,
        cylinder: 4,
        color:"blue"
    },
    {
        car_brand: "Tesla",
        car_model: "Model 3",
        car_price: 39000,
        car_image:'tesla-model-3.jpg',
        number_of_seats: 5,
        Drive_Type: "All-wheel drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Electric",
        Engine_size: "Electric",
        doors: 4,
        cylinder: 0,
        color:"red/blue"
    },
    {
        car_brand: "Porsche",
        car_model: "911",
        car_price: 11000,
        car_image:'porsche-911.jpg',
        number_of_seats: 4,
        Drive_Type: "Rear Wheel Drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: 3.0,
        doors: 2,
        cylinder: 6,
        color:"silver"
    },
    {
        car_brand: "Ferrari",
        car_model: "488 GTB",
        car_price: 30000,
        car_image:'ferrari488GTB.jpg',
        number_of_seats: 2,
        Drive_Type: "Rear Wheel Drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: 3.9,
        doors: 2,
        cylinder: 8,
        color:"red"
    },
    {
        car_brand: "Lamborghini",
        car_model: "Huracan",
        car_price: 24000,
        car_image:'lamboHurracan.jpg',
        number_of_seats: 2,
        Drive_Type: "All Wheel Drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: 5.2,
        doors: 2,
        cylinder: 10,
        color:"orangered"
    },
    {
        car_brand: "McLaren",
        car_model: "570S",
        car_price: 19000,
        car_image:'mclaren-570s.jpg',
        number_of_seats: 2,
        Drive_Type: "Rear Wheel Drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: 3.8,
        doors: 2,
        cylinder: 8,
        color:"orange"
    },
    {
        car_brand: "Bugatti",
        car_model: "Chiron",
        car_price: 30000,
        car_image:'BuggatiChiron.jpg',
        number_of_seats: 2,
        Drive_Type: "All Wheel Drive",
        transmission: "Automatic",
        year: 2023,
        fuel_type: "Gasoline",
        Engine_size: 8.0,
        doors: 2,
        cylinder: 16,
        color:"black"
    }
    
    ]
  

export default CarData;